### ISSUE TITLE
Curation history page just like: /@demo/trail

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#1157]
where we show latest voted posts by account and show content as in feed format, it will likely require fetching get_post or get_content of each author/permlink combination returned by get_account_history

**Comment by igormuba** [comment]
@feruzm  just to make sure.

The goal is that, if I enter in someone else's profile, there will be another section
![image](https://user-images.githubusercontent.com/21374091/207714418-0a7c63bd-70ba-46c7-ae1d-81d7dfd269e1.png)

I see every content that said someone else has upvoted or downvoted, right? Bot only votes, no reblogs or anything else, correct?

**Comment by igormuba** [comment]
@feruzm I am working on this on the branch
https://github.com/ecency/ecency-vision/tree/curation-page-history-1157

But I am struggling to understand how blog,posts, comments and replies are fetched so that I can populate the new tab with the correct data

If I manage to understand how that part works it would be a huge advance for me to understand the app, would be a huge progress to figure out all that

**Comment by igormuba** [comment]
Works, but still need to refine by adding:
- Pagination
- If the logged in user has voted/reblogged the loaded posts

https://github.com/ecency/ecency-vision/commit/cca9e3a30dd4a997b442d10841f3b47baa9c96c2

**Comment by igormuba** [comment]
Also: 
If the user of the trail removes the vote, keep the post or remove it from the trail. Will develop considering it should be removed and not shown on the trail.
