### ISSUE TITLE
Mobile Sign-in & Sign-up screen images do not fit in the screen

### ISSUE THREAD

**Issue by benas-maurusaitis** [ecency/ecency-vision#1261]
Tested with iOS and Android

![image](https://user-images.githubusercontent.com/55082182/223697214-006ffa95-b816-411f-82c6-a958bfe0f556.png)

![image](https://user-images.githubusercontent.com/55082182/223696313-22f8b612-1da4-4d9b-988b-1c4f9cfdc537.png)

**Comment by shawnpringle** [comment]
Perhaps it would be helpful to have the make and model numbers for these.
It looks like the one reporting the problem is on the /signup URL, but I am
unable to reproduce these on the production site.  Brave Development
Environment fails to show this problem in my fork, which may indicate a
regression in the Ecency code base.  If it is not that, it must be a
problem with Brave Development not emulating the phones well enough.

BaIn fact I cannot reproduce it in the production version of Ecency, so
baring a problem with the development environment itself, the problem must
be between either my latest fork to now, or between the last deployment of
Ecency to now.  I am using Brave Development to emulate iPhone SE and Pixel
5 and various screen widths.

Someone check the head ....

**Comment by feruzm** [comment]
@benas-maurusaitis and @shawnpringle I have moved issue other to mobile app repository. This is website repository and this report is not related to that. Mobile app repository is here and issue moved to that: https://github.com/ecency/ecency-mobile/issues/2632
