### ISSUE TITLE
Mobile friendly witnesses screen

### ISSUE THREAD

**Issue by feruzm** [ecency/ecency-vision#775]
Make /witnesses screen more mobile friendly.

**Comment by adilrime17** [comment]
![image](https://user-images.githubusercontent.com/47079977/149905246-3319063b-ba52-48ca-b17f-94b22bb43c3d.png)
I and @mghazanfar were looking into the witnesses page and the improvement for the mobile screen could be cards for each table row instead of a table. But for that, we might need some mock UI for the card against each entry.
Please give feedback on this if you have any ideas in your mind.

**Comment by feruzm** [comment]
@adilrime17 I agree, how about we do it similar to `/communities` page? In that page notice how each community is listed on mobile device, similar to card.
